spring:
  profiles:
    active: db

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: false
    database: mysql
    defer-datasource-initialization: true
  # 처음 : ddl-auto: create / generate-ddl: true / spring.sql.init.mode: always
  # 처음 이후 : ddl-auto: update / spring.sql.init.mode: never

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  sql:
    init:
      mode: always